### ISSUE TITLE
Overflow on The Big Picture

### ISSUE THREAD

**Issue by Hozey** [StartBootstrap/startbootstrap-the-big-picture#1]
Thanks for the method of adding a background image for bootstrap 3 pages.  I'm using bootstrap 2.3.2.  I got the image to appear, but, as you can see from the attached screenshot, it extends below the footer when displayed on a screen larger than the content.  I've tried various ideas with overflow, but can't get rid of the excess image below the footer.  Any suggestions?

Thank you.
![screen shot 2015-01-26 at 11 50 11 am 2](https://cloud.githubusercontent.com/assets/1206451/5904991/48d0875e-a552-11e4-8997-050948a80a9e.png)

**Comment by davidtmiller** [comment]
Big Picture is more for a one screen sort of landing page. I would try taking a look at Full to see if that better suits your needs. A theme like Full will probably do what you're looking for a bit better.
